version: '3.9'

services:
  server:
    build:
      context: ./server
    image: voice-ai-server:dev
    container_name: voice-ai-server
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - PORT=3000
      - DATABASE_PATH=/app/data/voice-ai-documents.db
      # Add other server env vars as needed
    volumes:
      - ./server/data:/app/data
      - ./server/src/personas:/app/src/personas:ro
      - ./server/src/prompts:/app/src/prompts:ro
      - ./server/src/scenarios:/app/src/scenarios:ro
      - ./server/src/util:/app/src/util:ro
    restart: unless-stopped

  client:
    build:
      context: ./client
      args:
        VITE_API_URL: http://localhost:3000
    image: voice-ai-client:dev
    container_name: voice-ai-client
    ports:
      - "5173:80"
    environment:
      - VITE_API_URL=http://localhost:3000
    depends_on:
      - server
    restart: unless-stopped
